services:
  postgres:
    container_name: order-postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      PGDATA: /data/postgress
    volumes:
      - ./postgres-data:/data/postgress
    ports:
      - "5432:5432"
